language: python
python:
  - "3.4"
# command to run tests
#script: nosetests -v --nocapture tests_pipeline_caller.py


install: pip install codecov
#script: coverage run tests_pipeline_caller.py

before_script: echo $pipeline_token > pipeline.token
script: nosetests -v --with-coverage --nocapture tests_pipeline_caller.py

after_success:
  - codecov

